server:
  port: 0

springdoc:
  paths-to-exclude: /exchange/send,/agents/hubControl

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 50
          scheduler:
            instanceName: SonicQuartz
            instanceId: AUTO
          jobStore:
            isClustered: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  task:
    execution:
      pool:
        core-size: 16
        max-size: 100
        queue-capacity: 1000

robot:
  client:
    host: http://${SONIC_SERVER_HOST:127.0.0.1}:${SONIC_SERVER_PORT:80}
  img:
    success: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/suc.png"
    warning: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/warn.png"
    error: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/fail.png"

python:
#  path: "/app/sonic/pythonFiles/"
  path: "D:\\software\\sonic\\"
