# 一般不需要动，懂的可以自己定制
logging:
  file:
    name: logs/${spring.application.name}.log
    max-size: 1024MB
    max-history: 3
  level:
    org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol: ERROR
    org.apache.dubbo.registry.zookeeper.ZookeeperRegistry: ERROR
    org.apache.dubbo.config.ServiceConfig: ERROR
    org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport: ERROR
    org.apache.dubbo.config.DubboShutdownHook: ERROR
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    org.cloud.sonic.agent.registry.zookeeper.AgentZookeeperRegistry: ERROR
    org.apache.curator.framework.recipes.cache.NodeCache: OFF
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
