# 测试使用
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sonic;DB_CLOSE_DELAY=-1;MODE=MySQL;
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  global-config:
    banner: false
  configuration:
    cache-enabled: false
    localCacheScope: STATEMENT
# 看 h2 web 使用
server:
  port: 10000

sonic:
  database:
    dialect: h2
    init_script: "sql-script/h2/schema.sql"

