spring:
  ldap:
    base: ou=system
    username: 'uid=admin,ou=system'
    password: 'password'
    urls: ldap://127.0.0.1:10389
sonic:
  token:
    secret: sonic
    expireDay: 14
  user:
    register:
      enable: true
    normal:
      enable: true
    ldap:
      enable: true
      userId: cn
      userBaseDN: ou=users
