server:
  port: 8093

spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Sonic测试平台 - 文件中心"
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

gateway:
  host: "http://localhost:8094"

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3

knife4j:
  enable: true
  setting:
    enableHost: true
    enableHostText: "http://localhost:8094"
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT License | Copyright 2021-[ZhouYiXun/sonic-server](https://github.com/ZhouYixun/sonic-server/blob/main/LICENSE)

eureka:
  instance:
    instance-id: ${spring.application.name}(v${spring.version})-${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://sonic:tester@127.0.0.1:9090/eureka/}