server:
  port: 8093

spring:
  version: @project.version@
  application:
    name: @project.artifactId@
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

gateway:
  host: "http://localhost:8094"

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3

knife4j:
  info:
    title: "Sonic服务端 - 文件中心 Open API"
    description: "sonic-server-folder 服务API暂不开放。"
  enable: true
  setting:
    enableHost: true
    enableHostText: "http://localhost:8092"

eureka:
  instance:
    instance-id: ${spring.application.name}(v${spring.version})-${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://sonic:tester@127.0.0.1:9090/eureka/}