server:
  port: 3000

filter:
  white-list: /projects/list,/websockets,/users/login,/users/register,/users/loginConfig,/swagger,/v3/api-docs,/doc.html,/folder/upload,/keepFiles/,/imageFiles/,/recordFiles/,/logFiles/,/packageFiles/

knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: sonic-server-controller
        url: /api/controller/v3/api-docs?group=default
        service-name: sonic-server-controller
        context-path: /api/controller
        order: 1
      - name: sonic-server-folder
        url: /api/folder/v3/api-docs?group=default
        service-name: sonic-server-folder
        context-path: /api/folder
        order: 2

spring:
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 314572800
      routes:
        - id: controller
          uri: lb://sonic-server-controller
          predicates:
            - Path=/api/controller/**, /api/transport/**
          filters:
            - StripPrefix=2
        - id: folder
          uri: lb://sonic-server-folder
          predicates: Path=/api/folder/**
          filters:
            - StripPrefix=2
        - id: transport
          uri: lb:ws://sonic-server-controller
          predicates:
            - Path=/websockets/**
          filters:
            - StripPrefix=1

        - id: dev-controller
          uri: lb://sonic-server-controller
          predicates:
            - Path=/server/api/controller/**, /server/api/transport/**
          filters:
            - StripPrefix=3
        - id: dev-folder
          uri: lb://sonic-server-folder
          predicates: Path=/server/api/folder/**
          filters:
            - StripPrefix=3
        - id: dev-transport
          uri: lb:ws://sonic-server-controller
          predicates:
            - Path=/server/websockets/**
          filters:
            - StripPrefix=2