logging:
  file:
    name: logs/${spring.application.name}.log
    max-size: 1024MB
    max-history: 3
  level:
    com.gitee.sunchenbin.mybatis.actable.manager.system.SysMysqlCreateTableManagerImpl: ERROR
    com.gitee.sunchenbin.mybatis.actable.manager.handler.StartUpHandlerImpl: ERROR
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
