spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sonic?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    username: root
    password: Sonic!@#123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true