spring:
  ldap:
    base: ou=system
    username: 'uid=admin,ou=system'
    password: 'password'
    urls: ldap://127.0.0.1:10389
sonic:
  ldap:
    enable: false
    userId: cn
    userBaseDN: ou=users
